add Catalog, ProductCard, Image, Price, Textbox components
yuli-belitskaya/react_lessons pull request #1
Opened 2018-07-19 09:28 UTC by yuli-belitskaya

add server rendering

2018-07-20 07:35 UTC, index01d requested changes

2018-07-20 07:35 UTC, index01d commented on src/components/catalog.js
> +                <ProductCard product={item}/>
не был передан ключ key. Вероятно, в консоли отображается ошибка об этом?

2018-07-20 07:35 UTC, index01d commented on src/components/catalog.js
> +                <ProductCard product={item}/>
уместнее использовать map

2018-07-20 07:35 UTC, index01d commented on src/components/image.js
> +        return <img src={this.props.imageUrl} style={{width: this.props.width, height: this.props.height}} alt={this.props.title} />
предварительно можно деструктурировать свойства
`const { imageUrl, width, height } = this.props;`, тогда эта запись окажется читабельнее

2018-07-20 07:35 UTC, index01d commented on src/components/price.js
> +        return <div style={{ textAlign: 'center', fontSize: '30px', margin: '5px 0', fontWeight: 'bold', color: '#980214'}}>{this.props.price}</div>
стоит разбить по строкам

2018-07-20 07:35 UTC, index01d commented on src/components/price.js
> +        return <div style={{ textAlign: 'center', fontSize: '30px', margin: '5px 0', fontWeight: 'bold', color: '#980214'}}>{this.props.price}</div>
возможно, также стоит добавить валюту? можно также отформатировать цену (см https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)

2018-07-20 07:35 UTC, index01d commented on src/components/product_card.js
> +                <TextBox title={this.props.product.title}/>
title лучше передать как дочерний элемент

2018-07-20 07:35 UTC, index01d commented on src/constants/Products.js
> +        "width": "300px",
данные картинки оказались в общем объекте продукта. Возможно, стоит объединить под вложенный ключ image всю информацию о картинке

2018-07-20 07:41 UTC, yuli-belitskaya commented on src/components/product_card.js
> +                <TextBox title={this.props.product.title}/>
не очень поняла, что значит как дочерний элемент?

2018-07-24 13:40 UTC, index01d approved these changes
Есть замечания в PR, но принято

2018-07-24 13:40 UTC, index01d commented on src/components/image.js
> +        const { image, title } = this.props;
если здесь додеструктурировать:
`const { image: { imageUrl, width, height }, title } = this.props;`,
то ниже не придется везде писать image.*

2018-07-24 13:40 UTC, index01d commented on src/components/image.js
> +        return <img src={image.imageUrl} style={{width: image.width, height: image.height}} alt={title} />
получится `style={{ width, height }}`

2018-07-24 13:40 UTC, index01d commented on src/components/product_card.js
> +                <TextBox title={this.props.product.title}/>
Имеется ввиду children. То есть получится нечто вроде `<TextBox>{title}</TextBox>`,
```
const TextBox = ({ children }) => ...
```

2018-07-25 06:19 UTC, merged